### ISSUE TITLE
Not receiving FunctionID.ON_INTERIOR_VEHICLE_DATA notification

### ISSUE THREAD

**Issue by karinase11** [smartdevicelink/sdl_java_suite#1100]
I'm trying to determine whether the device is in NIGHT or DAY DisplayMode. App is subscribed to interiorVehicleData, but onNotified is never called. 

##### Reproduction Steps
 ```

sdlManager.addOnRPCNotificationListener(FunctionID.ON_INTERIOR_VEHICLE_DATA, new OnRPCNotificationListener() {
      @Override
      public void onNotified(RPCNotification notification) {
        OnInteriorVehicleData onInteriorVehicleData = (OnInteriorVehicleData) notification;
        Log.d("plotter", "In onNotified");       
      }
    });


 GetInteriorVehicleData interiorVehicleData = new GetInteriorVehicleData();
      interiorVehicleData.setModuleType(ModuleType.HMI_SETTINGS);
      interiorVehicleData.setSubscribe(true);
    sdlManager.sendRPC(interiorVehicleData);
    Log.d("plotter", "Is subscribed: "+interiorVehicleData.getSubscribe()+"");

```
##### Expected Behavior
after toggling NIGHT and DAY Display Mode in Manticore
receiving ON_INTERIOR_VEHICLE_DATA, and being able to read out onInteriorVehicleData.getModuleData().getHmiSettingsControlData().getDisplayMode() 

##### Observed Behavior
notification not received

##### OS & Version Information
* Android Version: 9.0
* SDL Android Version: 4.+
* Testing Against: Manticore

**Comment by BrettyWhite** [comment]
Hi, 

I'm pretty sure that the night/day toggle simply toggles the theme. I don't believe Manticore sends an RPC when that happens. @crokita may be able to comment on that, and it is something we can definitely consider if an app is subscribed for `ON_INTERIOR_VEHICLE_DATA`. I will leave this open until the Manticore team can confirm this. 

Thanks!

**Comment by karinase11** [comment]
Hi, 
thanks for replying quickly, I assumed you could get hold of the current Display Mode since it is listed in the Android Guide under "Remote Control" > HMI Settings marked Get/Set/Notification. I have also tried subscribing to ModuleType.RADIO and unfortunately it also does not trigger onNotified function for me. 

ON_VEHICLE_DATA notifications work as expected, only ON_INTERIOR_VEHICLE_DATA seem to cause this issue.

**Comment by BrettyWhite** [comment]
Ok,

Just to confirm: 1st, you are calling a `GetInteriorVehicleData` and setting `subscribe` to `true` for whatever module you want to listen for (such as `RADIO`)? The response listener for this should return a Success. 

Second, you will need a listener for `sdlManager.addOnRPCNotificationListener(FunctionID.ON_INTERIOR_VEHICLE_DATA ......`

Manticore should have all permissions available by default for these, so that shouldn't be an issue.

Just wanted to double check you are doing both of those things, mainly the setting subscribe to true, otherwise you won't get notifications.

**Comment by karinase11** [comment]
Hi,
yes that's what I'm doing, the code basically barely deviates from the guide. I receive a true on getSubscribe() but onNotified is never called subsequently.

**Comment by joeygrover** [comment]
First, did you follow the guides that say to check the system capability manager to ensure the connected device actually supports remote control and the modules you are trying to access? 

From the guides:

```java
if (sdlManager.getSystemCapabilityManager().isCapabilitySupported(SystemCapabilityType.REMOTE_CONTROL)){
    // Since the module does support this capability we can query it for more information
    sdlManager.getSystemCapabilityManager().getCapability(SystemCapabilityType.REMOTE_CONTROL, new OnSystemCapabilityListener(){

        @Override
        public void onCapabilityRetrieved(Object capability){
            RemoteControlCapabilities remoteControlCapabilities = (RemoteControlCapabilities) capability;
            // Now it is possible to get details on how this capability 
            // is supported using the remoteControlCapabilities object
        }

        @Override
        public void onError(String info){
            Log.i(TAG, "Capability could not be retrieved: "+ info);
        }
    });
}
```

When you say ` I receive a true on getSubscribe()` are you simply checking the RPC message that you sent? Because you would have already set that to true, therefore it will always return true. You have to set a response listener for that RPC and determine if it was successful or not. You should have something like the following for Radio:

```java
		GetInteriorVehicleData interiorVehicleData = new GetInteriorVehicleData();
		interiorVehicleData.setModuleType(ModuleType.RADIO);
		interiorVehicleData.setSubscribe(true);
		interiorVehicleData.setOnRPCResponseListener(new OnRPCResponseListener() {
			@Override
			public void onResponse(int correlationId, RPCResponse response) {
				GetInteriorVehicleDataResponse getResponse = (GetInteriorVehicleDataResponse) response;
				//This can now be used to retrieve data
			}

			@Override
			public void onError(int correlationId, Result resultCode, String info) {
				Log.e(TAG, "GetInteriorVehicleData onError: " + resultCode);
			}
		});
                sdlManager.sendRPC(interiorVehicleData);


```

**Comment by karinase11** [comment]
Hi, works now, thanks for the support!
