### ISSUE TITLE
Multiple SoftButtons with same initial state

### ISSUE THREAD

**Issue by iCollin** [smartdevicelink/sdl_java_suite#1199]
### Bug Report
The `SoftButtonManager` exhibits weird behavior when calling `sdlManager.getScreenManager().setSoftButtonObjects($)` with an array containing multiple soft buttons which have the same initial state.

##### Reproduction Steps
1. Create two `SoftButtonObject`s which both include the same `SoftButtonState` in their `states` array and both specify the name of this `SoftButtonState` in the `initialStateName` field.
2. Call `sdlManager.getScreenManager().setSoftButtonObjects($)` with an array that includes both of the `SoftButtonObject`s created in step one.
3. Observe the second `UI.Show` RPC sent by the `SoftButtonManager` (once the images have been uploaded).

##### Expected Behavior
Each `SoftButtonObject` will have a unique `softButtonID`.

##### Observed Behavior
Both `SoftButtonObjects` will be assigned the `softButtonID` of the last `SoftButtonObject` in the list which has the same `initialState`.

##### OS & Version Information
* SDL Android Version: develop (commit 1b57bdc3c71475a9b2c071ebdfdc805cc1dff32e)
* Testing Against: SDL Core 6.0, Generic HMI 0.7

##### Test Case, Sample Code, and / or Example App
[Here is a gist](https://gist.github.com/iCollin/7d2dd4e654c786d7917196668f919977) with the function I used to reproduce this issue.

**Comment by bilal-alsharifi** [comment]
Thanks for reporting the issue @iCollin. That happens because `SoftButton` struct is stored in the `SoftButtonState`. So reusing a `SoftButtonState` in multiple objects, will make the object also resue the `SoftButton` struct which has the id stored in it.
Practically, developers shouldn't reuse the same states for multiple objects. We update the javadoc for the `SoftbuttonObject` to reflect that.
