### ISSUE TITLE
NPL in TransportBrokerImpl.resetSession()

### ISSUE THREAD

**Issue by yingchun1** [smartdevicelink/sdl_java_suite#1225]
SDL version 4.8.1
We collect follow exception in our crash service, please help to fix
'void com.smartdevicelink.transport.TransportManager$TransportBrokerImpl.resetSession()' on a null object reference at com.smartdevicelink.transport.TransportManager.resetSession(SourceFile_117) at com.smartdevicelink.protocol.SdlProtocolBase.resetSession(SourceFile_189) at com.smartdevicelink.SdlConnection.SdlSession2.resetSession(SourceFile_111) at com.smartdevicelink.proxy.SdlProxyBase.cleanProxy(SourceFile_1724) at com.smartdevicelink.proxy.SdlProxyBase.access$900(SourceFile_164) at com.smartdevicelink.proxy.SdlProxyBase$SdlInterfaceBroker.onProtocolSessionStarted(SourceFile_608) at com.smartdevicelink.SdlConnection.SdlSession.onProtocolSessionStarted(SourceFile_600) at com.smartdevicelink.protocol.SdlProtocolBase.handleProtocolSessionStarted(SourceFile_1060) at com.smartdevicelink.protocol.SdlProtocolBase$MessageFrameAssembler.handleControlFrame(SourceFile_1362) at com.smartdevicelink.protocol.SdlProtocolBase$MessageFrameAssembler.handleFrame(SourceFile_1319)

**Comment by jordynmackool** [comment]
@yingchun1 can you please update the issue to follow the template shown below:

### Bug Report
[Summary]

##### Reproduction Steps
1. [Step 1]
2. [Step 2]
3. [Step 3]

##### Expected Behavior
[Some expected behavior]

##### Observed Behavior
[Some observed behavior]

##### OS & Version Information
* Android Version: [What version of Android are you using when the bug occurred]
* SDL Android Version: [What version of the library has this bug been seen on]
* Testing Against: [What you tested with to observe this behavior]

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]
