### ISSUE TITLE
SDL Manager causing NullPointerException

### ISSUE THREAD

**Issue by khburdette** [smartdevicelink/sdl_java_suite#1228]
### Bug Report
SDL managers aren't ready before onStart is called, which is causing a NullPointerException

##### Reproduction Steps
1. Connect device to SDL via Bluetooth

##### Expected Behavior
App loads

##### Observed Behavior
App crashes with NullPointerException
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.smartdevicelink.managers.SdlManager.addOnRPCNotificationListener(com.smartdevicelink.protocol.enums.FunctionID, com.smartdevicelink.proxy.rpc.listeners.OnRPCNotificationListener)' on a null object reference
```

##### OS & Version Information
* Android Version: 9
* SDL Android Version: 4.9.1
* Testing Against: SYNC 3 head unit running software version 3.0

##### Test Case, Sample Code, and / or Example App
```
SdlManagerListener listener = new SdlManagerListener() {
	@Override
	public void onStart() {
		sdlManager.addOnRPCNotificationListener(FunctionID.ON_HMI_STATUS, new OnRPCNotificationListener() {
			@Override
			public void onNotified(RPCNotification notification) {
```

**Comment by joeygrover** [comment]
I'm closing this issue because it is not an issue with the library. The exception being thrown is because the local variable `sdlManager` is null, not because the instance of `SdlManager` is null. It is logically impossible (if the integration was done correctly) that the `onStart` method of the `SdlManagerListener` is called without first creating an instance of the `SdlManager`. It is likely that the local reference  is never set to the instance created when setting the listener or is set to null at some point and you are experiencing a race condition. I would check your integration against our guides, and ensure that the `sdlManager` reference is properly set and not set to null before accessing it.

**Comment by khburdette** [comment]
Our app has gone through several test passes through our own validation team and submitted to Ford for their certification. This issue is reported to us as a blocking issue by Ford and we picked up the log through our App Center integration.

**Comment by joeygrover** [comment]
You should likely be submitting first to the SDLC for certification, however, the previous statement still stands. It is simply not logically possible.
