### ISSUE TITLE
Update how the Screen Manager removes a graphic from a template

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_java_suite#1320]
### Bug Report
Currently, the screen manager API uploads a transparent image and uses that image name whenever the graphic needs to be removed from the template. This is not necessary as we can just use an "empty" `Image` in the `graphic` or `secondaryGraphic` field of a `Show` request.

```
Show show = new Show();
show.setMainField1("removing graphic");
show.setGraphic(new Image("", ImageType.DYNAMIC));
sdlManager.sendRPC(show);
```

##### OS & Version Information
* Android Version: n/a
* SDL Android Version: 4.10
* Testing Against: n/a

**Comment by theresalech** [comment]
Closing this issue because it is not possible to set an "empty" image for the `secondaryGraphic` field of a `Show` request due to a long standing bug with Core. The screen manager will still need to use the current logic for clearing the `secondaryGraphic`, which means there will be two sets of logic for removing the image. It is possible to do so, but this increases the likelihood of introducing bugs.
