### ISSUE TITLE
TirePressure on SDL 2.1

### ISSUE THREAD

**Issue by peterkomar** [smartdevicelink/sdl_java_suite#1617]
### Bug Report

On the old devices with SDL 2.1 not able to get tire pressure with SDL java suite 4.12.2.
![Screenshot_20210207-120302_TirePressure](https://user-images.githubusercontent.com/6721436/107226390-bdc26c80-6a22-11eb-83ed-df90e2931446.jpg)

Head Unit does not respond to tire pressure requests. For other requests it responses correctly.

here the video with permissions:

https://user-images.githubusercontent.com/6721436/107225295-4a6c2b00-6a21-11eb-9cfd-732fc32c5f15.mp4

##### OS & Version Information
* Android Version: 9
* SDL Android Version: 4.12.2
* Testing Against: Sync 1.1

##### Test Case, Sample Code, and / or Example App
```
final GetVehicleData vdRequest = new GetVehicleData();
vdRequest.setTirePressure(true);
sendLog("Request for tire pressure ....");
vdRequest.setOnRPCResponseListener(new OnRPCResponseListener() {
	@Override
        public void onResponse(int correlationId, RPCResponse response) {
		if (response.getSuccess()) {
			sendLog("Successfully getting car data");
		} else {
			sendLog("Error getting car data");
		}

		sendLog("Result code: " + response.getResultCode().toString());
		sendLog("Response Info: " + response.getInfo());
		sendLog("correlationId: " + correlationId);

		GetVehicleDataResponse vehicleResponse = (GetVehicleDataResponse) response;
                 TireStatus tireStatus = vehicleResponse.getTirePressure(); 
		showTireStatus(tireStatus.getLeftFront(), "Front Left:");
		showTireStatus(tireStatus.getRightFront(), "Front Right:");
		showTireStatus(tireStatus.getLeftRear(), "Rear Left:");
		showTireStatus(tireStatus.getRightRear(), "Rear Right:");
	}
});
sdlManager.sendRPC(vdRequest);
```

**Comment by bilal-alsharifi** [comment]
TDK could be responding with errors. Try to implement the `onError()` in `OnRPCResponseListener` and see if you get any errors back from Core.

**Comment by peterkomar** [comment]
Thanks, @bilal-alsharifi, will try (I thought it is deprecated and everything should go over onResponse). Other question do you know why Fuel consumption is null when Fuel economy is enabled?

**Comment by bilal-alsharifi** [comment]
I agree that `onError` was confusing. That is why we deprecated it in versions pre 5.0 in preparation to remove it but I believe it was still getting called in versions pre 5.0. In the latest version (5.0) `onError` is completely removed and `onResponse` should be called whether there is a success or failure.

**Comment by bilal-alsharifi** [comment]
Regarding `Fuel Consumption`, it may be disallowed. I suggest also checking the `onError` to see Core's response.

**Comment by joeygrover** [comment]
To clarify further, the `onResponse` method is only called when a successful response is received pre 5.0. Errors were received only in `onError`. This was confusing and fixed in 5.0 with removing `onError` completely, however we deprecated the `onError` method in previous versions to prepare developers that a change was incoming. We couldn't start sending error cases to the `onResponse` method prior to a major version update as that could have caused breaking issues for developers. 

Please also be aware that vehicle data on those older modules can be finicky and it is likely unrelated to the library itself.

**Comment by peterkomar** [comment]
Thanks @joeygrover 

> Please also be aware that vehicle data on those older modules can be finicky and it is likely unrelated to the library itself.

Could you explain more? Is it means that I should make some raw requests because old Ford sync 1.1 doesn't understand some standard sdl requests?

**Comment by joeygrover** [comment]
The availability of data is going to depend on the RPC version that the module supports. You can check the[ RPC spec ](https://github.com/smartdevicelink/rpc_spec/blob/master/MOBILE_API.xml#L6670)for when data items were introduced and check the RAI response from the IVI to see what version of the RPC spec was negotiated. Moreover, the older modules also might not be able to retrieve the data as reliably as the newer module. You also need to make sure your app name and app id are whitelisted to access the specific data items you are requesting.

Please let us know if you received the onError callback, otherwise we will look to close this issue.

**Comment by peterkomar** [comment]
Thanks, @joeygrover. onError callback works as expected.
