### ISSUE TITLE
Where is the TCPTransportConfig class?

### ISSUE THREAD

**Issue by Jack-Stoller** [smartdevicelink/sdl_java_suite#1785]
### Bug Report
I can not figure out how to import the class for a `TCPTransportConfig`.  All the other classes that I've needed from SDL import automatically fine in Andriod Studio but it, and I can't find this class. I'm trying to use this to connect to manticore with this. I've looked at the `BaseTransportConfig` but haven't figured any way to get a `TCPTransportConfig` from it. I did notice the `transport.enums.TransportType.TCP` but haven't figured out how to use it. Can I create a `BaseTransportConfig` and set the type to TCP? Where do I enter the port and address? I'm fairly confident this is an issue with my code, not a bug. I'm assuming I missed something from the examples, but I've scoured the internet and can't find any way to fix it. 

##### Reproduction Steps
1. Create a new project and set up imports to SDL
2. Copy/Paste [quickstart java code](https://smartdevicelink.com/en/guides/android/getting-started/integration-basics-java/)
3. Copy in the line from [here](https://smartdevicelink.com/en/guides/android/getting-started/integration-basics-java/) or [here](https://smartdevicelink.com/resources/manticore/)
4. View Error

![image](https://user-images.githubusercontent.com/47873835/149606765-4ab03130-f1b0-4f34-9e44-5d92dd00d205.png)

##### Expected Behavior
Using an import like `import com.smartdevicelink.transport.TCPTransportConfig;` or `import com.smartdevicelink.transport.BaseTransportConfig;` to import the class as specified here:
https://smartdevicelink.com/en/docs/android/master/com/smartdevicelink/transport/TCPTransportConfig/#constructor-0

##### Observed Behavior
No imports in the transport section have anything to do with a TCPTransport.

##### OS & Version Information
* Android Version: 10Q
* SDL Android Version: 5.3.1 (`implementation 'com.smartdevicelink:sdl_java_se:5.3.1'`)

**Comment by joeygrover** [comment]
Closing as not an issue.

The correct import is in fact `import com.smartdevicelink.transport.TCPTransportConfig;`. This is the transport config that extends a `BaseTransportConfig` and therefore is an acceptable class to instantiate a transport config to pass to the `SdlManager.Builder`

Your issue is that you are importing the Java SE library which does not contain Android specific classes. So even when you try to import the classes your IDE can't access the files because they are not part of that distribution.
Change your gradle line to `implementation 'com.smartdevicelink:sdl_android:5.3.1'` and sync. 

For future issues during integration please use our Slack, found [here](https://slack.smartdevicelink.com/), as these issues are specifically for issues with the library itself.
