### ISSUE TITLE
Issue of Notification came from the SDL

### ISSUE THREAD

**Issue by yingchun1** [smartdevicelink/sdl_java_suite#918]
### Bug Report
Our user report that SDL keep spamming notification.

##### Reproduction Steps
1. Open our app.
2. Connect/Disconnect one bluetooth device(input keyboard). 

##### Expected Behavior
Only the first time show the notification if we connect to same device/existing device in history.

##### Observed Behavior
 It will keep show the SDL notification when bluetooth switch between connected and disconnected.

##### OS & Version Information
* Android Version: Android 8.0.0, Build.MODEL = SM-G950U
* SDL Android Version: Latest Version 4.7.1, and 4.6.2.

From the source code, SdlRouterService, it will startforeground service with FOREGROUND_TIMEOUT set to 10000/1000=10 ms, it works in most device that will not show the notification at all, but it dose show the notification in some specific devices, but user can not found what it is because it disappear in very shot time 10ms?

Screenshot from our end user:
![image](https://user-images.githubusercontent.com/20849782/47829494-c72fe980-ddc2-11e8-9436-c4a8dc621b3c.png)

**Comment by bilal-alsharifi** [comment]
This is not a bug. It is how the system is designed. The notification will be displayed and it will disappear after 10ms if 1-BT accessory has never connected to the phone before 2-If the BT accessory has connected to the phone before but it is not an sdl enabled accessory. In the previous two cases, the notification will be displayed and then disappear very quickly. In most cases, the users will not be able to see the notification because it disappears very quickly. In some cases, the notification may be visible for a short period of time. However, if the user installed a notification tracker app, then they will see the history for all notifications even if they get displayed only for 10ms.
